require "active_support/core_ext/integer/time"
require_relative "../../lib/logging/tagged_broadcast_logger"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Store uploaded files on Cloudflare R2 (dev bucket, see config/storage.yml).
  config.active_storage.service = :r2
  config.x.r2_bucket = "prisma-games-dev"
  config.x.r2_endpoint = "https://61c3cb00c5c14e2bbbc5a63af36e904d.r2.cloudflarestorage.com"
  config.x.r2_public_host = "https://pub-0091a86174474268ae5e5d4c32e2f76e.r2.dev"

  # Run Active Job through Solid Queue locally (mirrors production) so the
  # recurring scheduler in config/recurring.yml fires the Correios tracking poll
  # without a deploy. Needs the queue database (bin/rails db:prepare) and the
  # `jobs` process in Procfile.dev.
  config.active_job.queue_adapter = :solid_queue
  config.solid_queue.connects_to = { database: { writing: :queue } }

  if ENV["RAILS_LOG_TO_STDOUT"].present?
    config.solid_queue.silence_polling = true

    stdout_logger = ActiveSupport::TaggedLogging.logger($stdout)
    # Must be the tagged variant: ActiveSupport::BroadcastLogger only guards
    # against re-running a block in #dispatch, and #tagged goes through
    # method_missing instead, which runs it once per sink. ActiveJob wraps every
    # enqueue in tag_logger, so a two-sink broadcast enqueues the job twice and
    # the customer gets the e-mail twice.
    config.logger = Logging::TaggedBroadcastLogger.new(
      ActiveSupport::TaggedLogging.logger(Rails.root.join("log", "development.log")),
      stdout_logger
    )
    config.after_initialize { stdout_logger.level = Logger::INFO }
  end

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # Send Devise confirmation / password-reset mails to a local /cartas inbox
  # (mounted in config/routes.rb) instead of SMTP: zero-infra preview during
  # local development, and the email lives in its own tab so the focused app
  # tab is never replaced.
  config.action_mailer.delivery_method = :letter_opener_web
  config.action_mailer.perform_deliveries = true

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!

  # Allow LAN access (phones, client laptops on the same Wi-Fi) and Cloudflare
  # Tunnel previews (*.trycloudflare.com) without DNS-rebinding 403s.
  # Restricted to development; production still uses Rails' default host check.
  config.hosts << /\A(?:\d{1,3}\.){3}\d{1,3}\z/        # any IPv4 (covers LAN)
  config.hosts << /\A[\w-]+\.trycloudflare\.com\z/     # ad-hoc cloudflared URLs
  config.hosts << /\A[\w-]+\.ngrok(?:-free)?\.app\z/   # ngrok if you ever swap

  # When SHARE_MODE=1 (set by bin/share-dev), harden the dev server enough to
  # be safe behind a public tunnel: no source-leaking error pages, no remote
  # web-console REPL, no verbose query/view annotations. Basic auth + dev-only
  # path blocking are wired in config/initializers/share_mode.rb.
  if ENV["SHARE_MODE"] == "1"
    config.consider_all_requests_local           = false
    config.action_dispatch.show_exceptions       = :rescuable
    config.action_view.annotate_rendered_view_with_filenames = false
    config.active_record.verbose_query_logs      = false
    config.action_dispatch.verbose_redirect_logs = false
    config.active_job.verbose_enqueue_logs       = false
    config.server_timing                         = false
    # web-console treats 127.0.0.1 as trusted; tunneled requests appear local,
    # so explicitly empty the allow-list to disable the REPL entirely.
    config.web_console.permissions = "::" if config.respond_to?(:web_console)
  end
end
