load Rails.root.join("db/seeds/store_setting.rb")
load Rails.root.join("db/seeds/catalog.rb")
load Rails.root.join("db/seeds/hero_banner.rb")
load Rails.root.join("db/seeds/recommendations.rb")
load Rails.root.join("db/seeds/game_of_the_month.rb")
load Rails.root.join("db/seeds/backoffice_demo.rb")
